name: 'Chromatic Deployment'
on: push

jobs:
  build:
    name: 'Build and Deploy to Chromatic'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 获取完整的 Git 历史记录

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deploy to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: 'build-storybook'
