name: 'Chromatic Deployment'
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Build and Deploy to Chromatic'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 获取完整的 Git 历史记录

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deploy to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: 'build-storybook'
      
      - name: Build Vue App
        run: yarn build

      - name: Deploy Vue App to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main # 部署到 gh-pages 分支
          folder: dist # Vue 应用构建输出目录

      - name: Deploy Storybook to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main # 部署到同一个 gh-pages 分支
          folder: .storybook-static # Storybook 构建输出目录
          target-folder: storybook # 部署到子路径

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master 
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}